#### general settings
solver: 'ADMM'
method: 'Primal'
is_regularized: True
delta: 0.000001
epsilon: 0.01
mode: 'Caffa'
dim_n: 1000
dim_m: 1000
rhos: [3.]
max_iter_step: 2000
iter_thre: 0.01
alpha: 1.618
class: 'WhiteNoise'